version: '3'
services:
  geth:
    image: danieldim12/my-image:latest 
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data:/root/.ethereum
    command: --http --http.addr 0.0.0.0 --http.api personal,eth,net,web3 --ws --ws.addr 0.0.0.0 --ws.api personal,eth,net,web3 --ws.origins "*"
