version: '3.8'

services:
  devnet:
    image: danieldim12/my-image:latest  # Use your newly built Docker image
    container_name: devnet_container
    restart: unless-stopped
    ports:
      - "8545:8545"  # Example port mapping, adjust as necessary
    volumes:
      - ./data:/data  # Example volume mount for data persistence
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
 
