version: '3.8'

services:
  devnet:
    image: danieldim12/my-image:latest 
    container_name: devnet_container #new
    restart: unless-stopped
    ports:
      - "8545:8545"  
    volumes:
      - ./data:/data  
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
 
