name: Build & push

on:
  push:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./go-ethereum/

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    environment: production
    
    #if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Build')

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          echo "The building of a new docker image is going to start now."
          docker build . --file Dockerfile1 --tag my-image:${{ github.event.number }} --push

      - name: Push Docker image to registry
        run: |
          docker tag my-image:${{ github.event.number }} danieldim12/my-picture:${{ github.event.number }}
          docker push danieldim12/my-picture:${{ github.event.number }}   
