name: Build & push

on:
  pull_request:
    types: [labeled]
    label: ['CI:Build']
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: ./go-ethereum/

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Build')

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the app image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: danieldim12/limechainImage:latest  
          secrets: |
            "secret_1=${{ secrets.MY_SECRET_1 }}"
            "secret_2=${{ secrets.MY_SECRET_2 }}"
