name: Build & push
on:
  pull_request:
    branches: 
      - master
    types: [closed]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./go-ethereum/

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: danieldim12/my-image:latest  
          secrets: |
            "secret_1=${{ secrets.MY_SECRET_1 }}"
            "secret_2=${{ secrets.MY_SECRET_2 }}"
