name: Deploy Contracts

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels[*].name == 'CI:Deploy'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run local devnet
        run: |
          docker-compose up -d geth
          
      - name: Deploy contracts
        run: npx hardhat run scripts/sample-script.js --network localhost
        
      - name: Build Docker image with deployed contracts
        run: |
          docker build -t my-image .
      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: danieldim12/my-image:latest

      - name: Run Hardhat tests
        run: |
          docker run -p 8545:8545 -d my-image:latest
          sleep 10 
          npx hardhat test
