name: Deploy Contracts

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.labels[*].name == 'CI:Deploy'
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Installing dependencies
        run: npm ci
        
      - name: Setting Up an Ethereum Proof-of-Stake Devnet 
        run: |
          git clone https://github.com/Offchainlabs/eth-pos-devnet
          cd eth-pos-devnet/consensus/
          echo "ELECTRA_FORK_VERSION: 0x20000094" >> config.yml
          cd ../
          docker compose up -d

      - name: what
        run: |
          pwd
          pwd
          ls -la
          cd hardhat/ignition/modules/ && ls -la && pwd
          
      - name: Deploy contracts
        working-directory: /hardhat
        run: |
          # # working-directory: ./go-ethereum/
          # sudo chmod 0700 -R /hardhat
          # cd hardhat/
          sudo chmod 0700 -R ./ignition/modules
          npx hardhat ignition deploy ./ignition/modules/Token.js --network eth-pos-devnet_default
          
          # npx hardhat run scripts/sample-script.js --network localhost
        
      - name: Build Docker image with deployed contracts
        run: |
          docker build -t my-image .
      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: danieldim12/my-image:latest

      - name: Run Hardhat tests
        run: |
          docker run -p 8545:8545 -d my-image:latest
          sleep 10 
          npx hardhat test
