name: Build & push
on:
  pull_request:
    branches: 
      - master
    types: [closed, labeled ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./go-ethereum/

jobs:
  lime-pline:
   # if: github.event.pull_request.merged == true && github.event.pull_request.label.name == 'CI:Build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the app image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: danieldim12/my-image:latest  
